//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingCooperative
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counters
    {
        public int IdCounter { get; set; }
        public int TypeCounter { get; set; }
        public int House { get; set; }
        public int Information { get; set; }
    
        public virtual Houses Houses { get; set; }
        public virtual TypesOfCounters TypesOfCounters { get; set; }
    }
}
