//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingCooperative
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnersOfHouses
    {
        public int IdOwnersOfHouses { get; set; }
        public int Owner { get; set; }
        public int House { get; set; }
        public System.DateTime DatePayment { get; set; }
        public int StatusOwner { get; set; }
        public Nullable<bool> IsHolder { get; set; }
    
        public virtual Houses Houses { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
