//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingCooperative
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rates()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int IdRate { get; set; }
        public int TypeOfPayment { get; set; }
        public decimal Rate { get; set; }
        public string Unit { get; set; }
        public int MonthBegin { get; set; }
        public int YearBegin { get; set; }
        public int StatusRate { get; set; }
    
        public virtual StatusesOfRates StatusesOfRates { get; set; }
        public virtual TypesOfPayment TypesOfPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
